name: ev_charging_stations
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  get: ^4.6.6
  get_storage: ^2.1.1 

  flutter_native_splash: ^2.3.5
  smooth_page_indicator: ^1.1.0

  google_maps_flutter: ^2.5.0

  # Icons.
  cupertino_icons: ^1.0.2

  # firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0

  # Razorpay
  razorpay_flutter: ^1.3.6

  fluttertoast: ^8.2.4

  geolocator: ^10.1.0
  intl: ^0.19.0
  location: ^5.0.3
  flutter_rating_bar: ^4.0.1


  url_launcher: ^6.1.8
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # Local Assets
  assets:
    - assets/logo/logo.png
    - assets/img/onboarding_images/
    - assets/marker/ev_station.png
    - assets/evstation_charging.jpeg